### ISSUE TITLE
[angular-cli-hooks] Feature request: Support for dev-server

### ISSUE THREAD

**Issue by fidian** [blidblid/berglund#2]
Can you also supply hooks that would apply my code before/after the dev-server runs and before/after each individual build happens for the dev server?

**Comment by blidblid** [comment]
Since the file watcher that triggers rebuilds are internal to webpack, it'll be very tricky to do work before a rebuild. As is, it will work like this when hooking into `serve`:

> ng s

* Calling custom before-hook ->
* Building app ->
* Calling custom after-hook ->
* Rebuilding app ->
* Calling after-hook ->

**Comment by fidian** [comment]
That will work for me. It could trigger a second webpack if I update content, but I can live with that.
